def get_data():
    data = [
        {
            "entity_id": "ZQLjrNx",
            "title": "99 Insanely Helpful Word Shortcuts for PC and Mac",
            "subtitle": "",
            "description": "Save time and be more productive with the best Microsoft Word keyboard shortcuts for PC and Mac.",
            "custom_fields": "",
            "last_modified_ts": 1645044080,
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "cta_url": "https://betatest.degreed.com/books/?d=V8343Y66V9",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 0.0},
                {"name": "Content Type", "value": "Book"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Book",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "zQV100Q",
            "title": "Business Skills List: Top Skills to Thrive in Any Workplace",
            "subtitle": "",
            "description": "What are the top business skills that can help you thrive in any workplace environment? Check out this business skills list to find out.",
            "custom_fields": "",
            "last_modified_ts": 1645044089,
            "image_url": "https://cdn2.goskills.com/blobs/blogs/558/82665f83-83c4-443b-8604-52f74c71b8ab-hero.jpg",
            "cta_url": "https://betatest.degreed.com/articles/?d=M90R456XGP",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 0.23},
                {"name": "Content Type", "value": "Article"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Article",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "ZQLjrxR",
            "title": "100 Insanely Helpful PowerPoint Shortcuts for PC and Mac",
            "subtitle": "",
            "description": "Save time and be more productive with the best Microsoft PowerPoint keyboard shortcuts for PC and Mac.",
            "custom_fields": "",
            "last_modified_ts": 1645044080,
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "cta_url": "https://betatest.degreed.com/books/?d=49E45K332P",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 0.0},
                {"name": "Content Type", "value": "Book"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Book",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "ZQLjry6",
            "title": "200+ Best Excel Shortcuts for PC and Mac",
            "subtitle": "",
            "description": "Save time and be more productive with this list of the best Excel keyboard shortcuts for Windows and Mac.",
            "custom_fields": "",
            "last_modified_ts": 1645044080,
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "cta_url": "https://betatest.degreed.com/books/?d=DP643J66R8",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 0.0},
                {"name": "Content Type", "value": "Book"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Book",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "rwoA02k",
            "title": "Microsoft Word - Advanced",
            "subtitle": "",
            "description": "Learn advanced techniques in Microsoft Word via video tutorials from Certified Microsoft Office Specialist Andy Lanning with this personalized online course.",
            "custom_fields": "",
            "last_modified_ts": 1645044079,
            "image_url": "https://www.goskills.com/blobs/bags/54/new-share-card.png",
            "cta_url": "https://betatest.degreed.com/courses/?d=08GQKV30R9",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 1.65},
                {"name": "Content Type", "value": "Course"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Course",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "rwoAjdW",
            "title": "Microsoft Excel - Basic & Advanced",
            "subtitle": "",
            "description": "Learn Excel with this engaging online course. Master essential Excel skills with bite-sized training from an award-winning instructor. Get certified today!",
            "custom_fields": "",
            "last_modified_ts": 1645044079,
            "image_url": "https://www.goskills.com/blobs/bags/37/new-share-card.png",
            "cta_url": "https://betatest.degreed.com/courses/?d=K9O6127NX8",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 5.36},
                {"name": "Content Type", "value": "Course"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Course",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "rwoAjW0",
            "title": "Microsoft PowerPoint 2010-2019",
            "subtitle": "",
            "description": "Learn PowerPoint through video tutorials from two award-winning Microsoft MVPs with this personalized online course.",
            "custom_fields": "",
            "last_modified_ts": 1645044079,
            "image_url": "https://www.goskills.com/blobs/bags/38/new-share-card.png",
            "cta_url": "https://betatest.degreed.com/courses/?d=E9JW7O3NOP",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 3.32},
                {"name": "Content Type", "value": "Course"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Course",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "zQV1jkB",
            "title": "Excel Challenge #13",
            "subtitle": "",
            "description": "Can you filter in Excel using multiple criteria and wildcards? Test your skills by stepping up to this challenge!",
            "custom_fields": "",
            "last_modified_ts": 1645044092,
            "image_url": "https://cdn2.goskills.com/blobs/blogs/562/5c020517-76ba-4f64-8711-44f0ea3b2389-hero.jpg",
            "cta_url": "https://betatest.degreed.com/articles/?d=08QWMLYK58",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 0.02},
                {"name": "Content Type", "value": "Article"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Article",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "zQV10vY",
            "title": "Excel Challenge #12",
            "subtitle": "",
            "description": "In this challenge, we are experimenting with different methods of splitting data in Excel. How many methods do you know? Which method is most efficient?",
            "custom_fields": "",
            "last_modified_ts": 1645044094,
            "image_url": "https://cdn2.goskills.com/blobs/blogs/559/8ff5824c-bd2b-4fb6-aef8-602e0d141c02-hero.jpg",
            "cta_url": "https://betatest.degreed.com/articles/?d=39ZLR021XP",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 0.03},
                {"name": "Content Type", "value": "Article"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Article",
            "tags": "",
            "metadata": "",
        },
        {
            "entity_id": "zQV1p0B",
            "title": "How to Use the Excel Find Function",
            "subtitle": "",
            "description": "The Excel FIND function helps you look for something within a specific text string. Learn how in this tutorial.",
            "custom_fields": "",
            "last_modified_ts": 1645044087,
            "image_url": "https://cdn2.goskills.com/blobs/blogs/557/db565097-9a26-4e8c-9e69-377058241ec0-hero.jpg",
            "cta_url": "https://betatest.degreed.com/articles/?d=O97M3O60VP",
            "source_name": "Internal",
            "fields": [
                {"name": "Provider", "value": "Internal"},
                {"Name": "Durations Hours", "Value": 0.2},
                {"name": "Content Type", "value": "Article"},
                {"name": "Language", "value": "en"},
                {"name": "Owner", "value": None},
                {"name": "Published Date", "value": "16/02/2022"},
            ],
            "cta_label": "Article",
            "tags": "",
            "metadata": "",
        },
    ]
    return data
