def get_data_on_valid_term():
    data = [
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Save time and be more productive with the best Microsoft Word keyboard shortcuts for PC and Mac.",
            "language": "en",
            "title": "99 Insanely Helpful Word Shortcuts for PC and Mac",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "ZQLjrNx",
            "lms_data": "",
            "course_type": "Book",
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/books/?d=V8343Y66V9",
            "duration_hours": 0.0,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "What are the top business skills that can help you thrive in any workplace environment? Check out this business skills list to find out.",
            "language": "en",
            "title": "Business Skills List: Top Skills to Thrive in Any Workplace",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "zQV100Q",
            "lms_data": "",
            "course_type": "Article",
            "image_url": "https://cdn2.goskills.com/blobs/blogs/558/82665f83-83c4-443b-8604-52f74c71b8ab-hero.jpg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/articles/?d=M90R456XGP",
            "duration_hours": 0.23,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Save time and be more productive with the best Microsoft PowerPoint keyboard shortcuts for PC and Mac.",
            "language": "en",
            "title": "100 Insanely Helpful PowerPoint Shortcuts for PC and Mac",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "ZQLjrxR",
            "lms_data": "",
            "course_type": "Book",
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/books/?d=49E45K332P",
            "duration_hours": 0.0,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Save time and be more productive with this list of the best Excel keyboard shortcuts for Windows and Mac.",
            "language": "en",
            "title": "200+ Best Excel Shortcuts for PC and Mac",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "ZQLjry6",
            "lms_data": "",
            "course_type": "Book",
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/books/?d=DP643J66R8",
            "duration_hours": 0.0,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Learn advanced techniques in Microsoft Word via video tutorials from Certified Microsoft Office Specialist Andy Lanning with this personalized online course.",
            "language": "en",
            "title": "Microsoft Word - Advanced",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "rwoA02k",
            "lms_data": "",
            "course_type": "Course",
            "image_url": "https://www.goskills.com/blobs/bags/54/new-share-card.png",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/courses/?d=08GQKV30R9",
            "duration_hours": 1.65,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Learn Excel with this engaging online course. Master essential Excel skills with bite-sized training from an award-winning instructor. Get certified today!",
            "language": "en",
            "title": "Microsoft Excel - Basic & Advanced",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "rwoAjdW",
            "lms_data": "",
            "course_type": "Course",
            "image_url": "https://www.goskills.com/blobs/bags/37/new-share-card.png",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/courses/?d=K9O6127NX8",
            "duration_hours": 5.36,
        },
    ]
    return data


def get_data_on_valid_fq():
    data = [
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "",
            "language": "en",
            "title": "",
            "skills": "",
            "published_date": "",
            "lms_course_id": "",
            "lms_data": "",
            "course_type": None,
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "provider": "",
            "difficulty": "",
            "course_url": "",
            "duration_hours": "NA",
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Save time and be more productive with the best Microsoft Word keyboard shortcuts for PC and Mac.",
            "language": "en",
            "title": "99 Insanely Helpful Word Shortcuts for PC and Mac",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "ZQLjrNx",
            "lms_data": "",
            "course_type": "Book",
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/books/?d=V8343Y66V9",
            "duration_hours": 0.0,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "What are the top business skills that can help you thrive in any workplace environment? Check out this business skills list to find out.",
            "language": "en",
            "title": "Business Skills List: Top Skills to Thrive in Any Workplace",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "zQV100Q",
            "lms_data": "",
            "course_type": "Article",
            "image_url": "https://cdn2.goskills.com/blobs/blogs/558/82665f83-83c4-443b-8604-52f74c71b8ab-hero.jpg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/articles/?d=M90R456XGP",
            "duration_hours": 0.23,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Save time and be more productive with the best Microsoft PowerPoint keyboard shortcuts for PC and Mac.",
            "language": "en",
            "title": "100 Insanely Helpful PowerPoint Shortcuts for PC and Mac",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "ZQLjrxR",
            "lms_data": "",
            "course_type": "Book",
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/books/?d=49E45K332P",
            "duration_hours": 0.0,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Save time and be more productive with this list of the best Excel keyboard shortcuts for Windows and Mac.",
            "language": "en",
            "title": "200+ Best Excel Shortcuts for PC and Mac",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "ZQLjry6",
            "lms_data": "",
            "course_type": "Book",
            "image_url": "https://blog.degreed.com/wp-content/themes/degreed-blog/assets/img/new-logo.svg",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/books/?d=DP643J66R8",
            "duration_hours": 0.0,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Learn advanced techniques in Microsoft Word via video tutorials from Certified Microsoft Office Specialist Andy Lanning with this personalized online course.",
            "language": "en",
            "title": "Microsoft Word - Advanced",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "rwoA02k",
            "lms_data": "",
            "course_type": "Course",
            "image_url": "https://www.goskills.com/blobs/bags/54/new-share-card.png",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/courses/?d=08GQKV30R9",
            "duration_hours": 1.65,
        },
        {
            "status": "",
            "category": "",
            "group_id": "",
            "description": "Learn Excel with this engaging online course. Master essential Excel skills with bite-sized training from an award-winning instructor. Get certified today!",
            "language": "en",
            "title": "Microsoft Excel - Basic & Advanced",
            "skills": "",
            "published_date": "16/02/2022",
            "lms_course_id": "rwoAjdW",
            "lms_data": "",
            "course_type": "Course",
            "image_url": "https://www.goskills.com/blobs/bags/37/new-share-card.png",
            "provider": "Internal",
            "difficulty": "",
            "course_url": "https://betatest.degreed.com/courses/?d=K9O6127NX8",
            "duration_hours": 5.36,
        },
    ]
    return data
