def get_data():
    data = [
        {
            "status": "",
            "medium": "",
            "verified": False,
            "description": "",
            "language": "",
            "title": "AWS Trends to Watch for in 2021",
            "lms_course_id": "zQV15vW",
            "is_internal": True,
            "points_earned": "0.7093333",
            "course_url": "https://www.exitcertified.com/blog/aws-trends-to-watch-for-in-2021?reseller=7",
            "course_type": "Article",
            "completion_date": 1645056000,
            "provider": None,
            "data_json": "",
            "difficulty": "",
            "start_date": 1645089086,
        },
        {
            "status": "",
            "medium": "",
            "verified": False,
            "description": "",
            "language": "",
            "title": "The Top 10 Programming Languages in 2021",
            "lms_course_id": "zQV1w6Z",
            "is_internal": True,
            "points_earned": "1.2413333",
            "course_url": "https://www.exitcertified.com/blog/the-top-10-programming-languages-in-2021?reseller=7",
            "course_type": "Article",
            "completion_date": 1645056000,
            "provider": None,
            "data_json": "",
            "difficulty": "",
            "start_date": 1645090849,
        },
        {
            "status": "",
            "medium": "",
            "verified": False,
            "description": "",
            "language": "",
            "title": "Business Skills List: Top Skills to Thrive in Any Workplace",
            "lms_course_id": "zQV100Q",
            "is_internal": True,
            "points_earned": "0.6206667",
            "course_url": "https://www.goskills.com/Soft-Skills/Resources/Business-skills-list?utm_source=degreed",
            "course_type": "Article",
            "completion_date": 1646092800,
            "provider": None,
            "data_json": "",
            "difficulty": "",
            "start_date": 1646143809,
        },
    ]
    return data
