def get_data():
    data = [
        {
            "type": "content",
            "id": "ZQLjrNx",
            "attributes": {
                "content-type": "Book",
                "external-id": "ShortcutApp:2",
                "title": "99 Insanely Helpful Word Shortcuts for PC and Mac",
                "summary": "Save time and be more productive with the best Microsoft Word keyboard shortcuts for PC and Mac.",
                "url": "https://www.goskills.com/Microsoft-Office/Shortcuts/Word?utm_source=degreed",
                "format": None,
                "is-obsolete": False,
                "image-url": None,
                "language": "en",
                "duration": 0.0,
                "duration-type": "Pages",
                "provider": "Internal",
                "is-internal": True,
                "owner": None,
                "created-at": "2022-02-16T20:41:20.413",
                "modified-at": "2022-02-16T20:41:20.413",
                "degreed-url": "https://betatest.degreed.com/books/?d=V8343Y66V9",
            },
            "links": {"self": "https://api.betatest.degreed.com/api/v2/content/ZQLjrNx"},
        },
        {
            "type": "content",
            "id": "zQV100Q",
            "attributes": {
                "content-type": "Article",
                "external-id": "Blog:558",
                "title": "Business Skills List: Top Skills to Thrive in Any Workplace",
                "summary": "What are the top business skills that can help you thrive in any workplace environment? Check out this business skills list to find out.",
                "url": "https://www.goskills.com/Soft-Skills/Resources/Business-skills-list?utm_source=degreed",
                "format": None,
                "is-obsolete": False,
                "image-url": "https://cdn2.goskills.com/blobs/blogs/558/82665f83-83c4-443b-8604-52f74c71b8ab-hero.jpg",
                "language": "en",
                "duration": 3500.0,
                "duration-type": "Words",
                "provider": "Internal",
                "is-internal": True,
                "owner": None,
                "created-at": "2022-02-16T20:41:19.43",
                "modified-at": "2022-02-16T20:41:29.32",
                "degreed-url": "https://betatest.degreed.com/articles/?d=M90R456XGP",
            },
            "links": {"self": "https://api.betatest.degreed.com/api/v2/content/zQV100Q"},
        },
        {
            "type": "content",
            "id": "ZQLjrxR",
            "attributes": {
                "content-type": "Book",
                "external-id": "ShortcutApp:3",
                "title": "100 Insanely Helpful PowerPoint Shortcuts for PC and Mac",
                "summary": "Save time and be more productive with the best Microsoft PowerPoint keyboard shortcuts for PC and Mac.",
                "url": "https://www.goskills.com/Microsoft-Office/Shortcuts/PowerPoint?utm_source=degreed",
                "format": None,
                "is-obsolete": False,
                "image-url": None,
                "language": "en",
                "duration": 0.0,
                "duration-type": "Pages",
                "provider": "Internal",
                "is-internal": True,
                "owner": None,
                "created-at": "2022-02-16T20:41:20.4",
                "modified-at": "2022-02-16T20:41:20.4",
                "degreed-url": "https://betatest.degreed.com/books/?d=49E45K332P",
            },
            "links": {"self": "https://api.betatest.degreed.com/api/v2/content/ZQLjrxR"},
        },
        {
            "type": "content",
            "id": "ZQLjry6",
            "attributes": {
                "content-type": "Book",
                "external-id": "ShortcutApp:1",
                "title": "200+ Best Excel Shortcuts for PC and Mac",
                "summary": "Save time and be more productive with this list of the best Excel keyboard shortcuts for Windows and Mac.",
                "url": "https://www.goskills.com/Excel/Shortcuts/Reference?utm_source=degreed",
                "format": None,
                "is-obsolete": False,
                "image-url": None,
                "language": "en",
                "duration": 0.0,
                "duration-type": "Pages",
                "provider": "Internal",
                "is-internal": True,
                "owner": None,
                "created-at": "2022-02-16T20:41:20.413",
                "modified-at": "2022-02-16T20:41:20.413",
                "degreed-url": "https://betatest.degreed.com/books/?d=DP643J66R8",
            },
            "links": {"self": "https://api.betatest.degreed.com/api/v2/content/ZQLjry6"},
        },
        {
            "type": "content",
            "id": "rwoA02k",
            "attributes": {
                "content-type": "Course",
                "external-id": "Course:19",
                "title": "Microsoft Word - Advanced",
                "summary": "Learn advanced techniques in Microsoft Word via video tutorials from Certified Microsoft Office Specialist Andy Lanning with this personalized online course.",
                "url": "https://www.goskills.com/Course/Microsoft-Word-Advanced?utm_source=degreed",
                "format": None,
                "is-obsolete": False,
                "image-url": "https://www.goskills.com/blobs/bags/54/new-share-card.png",
                "language": "en",
                "duration": 5922.0,
                "duration-type": "Seconds",
                "provider": "Internal",
                "is-internal": True,
                "owner": None,
                "created-at": "2022-02-16T20:41:19.447",
                "modified-at": "2022-02-16T20:41:19.4",
                "degreed-url": "https://betatest.degreed.com/courses/?d=08GQKV30R9",
            },
            "links": {"self": "https://api.betatest.degreed.com/api/v2/content/rwoA02k"},
        },
        {
            "type": "content",
            "id": "rwoAjdW",
            "attributes": {
                "content-type": "Course",
                "external-id": "Course:1",
                "title": "Microsoft Excel - Basic & Advanced",
                "summary": "Learn Excel with this engaging online course. Master essential Excel skills with bite-sized training from an award-winning instructor. Get certified today!",
                "url": "https://www.goskills.com/Course/Excel?utm_source=degreed",
                "format": None,
                "is-obsolete": False,
                "image-url": "https://www.goskills.com/blobs/bags/37/new-share-card.png",
                "language": "en",
                "duration": 19283.0,
                "duration-type": "Seconds",
                "provider": "Internal",
                "is-internal": True,
                "owner": None,
                "created-at": "2022-02-16T20:41:19.383",
                "modified-at": "2022-02-16T20:41:19.367",
                "degreed-url": "https://betatest.degreed.com/courses/?d=K9O6127NX8",
            },
            "links": {"self": "https://api.betatest.degreed.com/api/v2/content/rwoAjdW"},
        },
        {
            "type": "content",
            "id": "rwoAjW0",
            "attributes": {
                "content-type": "Course",
                "external-id": "Course:2",
                "title": "Microsoft PowerPoint 2010-2019",
                "summary": "Learn PowerPoint through video tutorials from two award-winning Microsoft MVPs with this personalized online course.",
                "url": "https://www.goskills.com/Course/PowerPoint-2016?utm_source=degreed",
                "format": None,
                "is-obsolete": False,
                "image-url": "https://www.goskills.com/blobs/bags/38/new-share-card.png",
                "language": "",
                "duration": 11947.0,
                "duration-type": "Seconds",
                "provider": "Internal",
                "is-internal": True,
                "owner": None,
                "created-at": "2022-02-16T20:41:19.383",
                "modified-at": "2022-02-16T20:41:19.353",
                "degreed-url": "https://betatest.degreed.com/courses/?d=E9JW7O3NOP",
            },
            "links": {"self": "https://api.betatest.degreed.com/api/v2/content/rwoAjW0"},
        },
    ]
    return data
