name: Pylint
on: [push]
jobs:
  build:
    #disable=line-too-long 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install requests
        pip install furl
    - name: Analysing the code with pylint
      run: |
        #disable=C0301
        find . -name 'lambda_function.py' -exec pylint {} \;
